// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RealEstateAds.Dal.Demo;

namespace RealEstateAdsAPI.Migrations
{
    [DbContext(typeof(DemoContext))]
    [Migration("20181008160352_DemoInitialMigration")]
    partial class DemoInitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Demo")
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("RealEstateAds.Dal.Demo.Entities.Ads.DemoFlatAd", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long?>("FlatId");

                    b.Property<string>("Phone");

                    b.Property<decimal>("Price");

                    b.HasKey("Id");

                    b.HasIndex("FlatId");

                    b.ToTable("FlatAds");
                });

            modelBuilder.Entity("RealEstateAds.Dal.Demo.Entities.RealEstateObjects.DemoFlat", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("City");

                    b.Property<string>("Country");

                    b.Property<int>("Floor");

                    b.Property<int>("Rooms");

                    b.HasKey("Id");

                    b.ToTable("Flats");
                });

            modelBuilder.Entity("RealEstateAds.Dal.Demo.Entities.Ads.DemoFlatAd", b =>
                {
                    b.HasOne("RealEstateAds.Dal.Demo.Entities.RealEstateObjects.DemoFlat", "Flat")
                        .WithMany("Ads")
                        .HasForeignKey("FlatId");
                });
#pragma warning restore 612, 618
        }
    }
}
